package SerigrafiaTorres;

import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Ian
 */
public class borrarUsuario extends javax.swing.JFrame {
    
    private ConexionMySQL mysql = new ConexionMySQL();
    private DefaultListModel lista = new DefaultListModel();
    /**
     * Creates new form borrarUsuario
     */
    public borrarUsuario() {
        initComponents();
        
        llenarLista();
    }
    
    private void llenarLista(){
        
        lista.clear();
        
        mysql.crearConexion(false);
        
        String sql = "SELECT * FROM usuarios";
        
        ResultSet resul = mysql.ejecutarConsulta(sql);
        
        try{
            while(resul.next()){
                lista.addElement(resul.getString("nombre"));
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error de SQL" + e.getMessage(),
            "Error de SQL", JOptionPane.ERROR_MESSAGE);
        }
        jlUsuarios.setModel(lista);
        
        mysql.cerrarConexion();
    }
    
    public void limpiar(){
        jlNombre.setText("");
        jlNomUsuario.setText("");
        jlID.setText("");
        
        jlUsuarios.removeSelectionInterval(0, jlUsuarios.getMinSelectionIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlUsuarios = new javax.swing.JList<>();
        bRegresar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlNomUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Borrar Usuario");

        jLabel1.setText("Bienvenido al menu de Borrar Usuarios");

        jlUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlUsuarios);

        bRegresar.setText("Regresar");
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre del Empleado:");

        jLabel3.setText("Nombre de usuario:");

        jLabel4.setText("ID del Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(bRegresar))
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNomUsuario)
                                    .addComponent(jlNombre)
                                    .addComponent(jlID))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(bBorrar)
                                .addGap(64, 64, 64))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlNomUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegresar)
                    .addComponent(bBorrar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        Principal principal = new Principal();
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_bRegresarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        if(!jlID.getText().isEmpty()){
            
            mysql.crearConexion(false);
            
            String sql = "DELETE FROM usuarios WHERE id_usuario = " + jlID.getText();
            
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el usuario? No se podra recuperar...",
                    "Eliminar registro", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
            if(JOptionPane.YES_OPTION == confirmar){
                mysql.actualizarRegistro(sql);
            }
            mysql.cerrarConexion();
            
            limpiar();
            
            mysql.cerrarConexion();
            
            llenarLista();
        }else{
            JOptionPane.showMessageDialog(null, "Parece que no has seleccionado ningun usuario!",
                    "Atencion", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void jlUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlUsuariosMouseClicked
        mysql.crearConexion(false);
        
        String sql = "SELECT * FROM usuarios WHERE nombre = '" +
                jlUsuarios.getSelectedValue().toString() + "'";
        
        ResultSet resul = mysql.ejecutarConsulta(sql);
        
        try{
            resul.first();
            jlNombre.setText(resul.getString("nombre"));
            jlNomUsuario.setText(resul.getString("usuario"));
            jlID.setText(resul.getString("id_usuario"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error de SQL:" + e.getMessage(),
                    "Error de SQL", JOptionPane.ERROR_MESSAGE);
        }
        mysql.cerrarConexion();
    }//GEN-LAST:event_jlUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNomUsuario;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JList<String> jlUsuarios;
    // End of variables declaration//GEN-END:variables
}
