package SerigrafiaTorres;

import java.sql.*;

import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ian
 */
public class mirarRegistro extends javax.swing.JFrame {

    private ConexionMySQL mysql = new ConexionMySQL();
    private DefaultTableModel modeloDatos = new DefaultTableModel();
    private DefaultListModel pedidos = new DefaultListModel();
    private String sql;
    private String busqueda = "";
    
    /**
     * Creates new form mirarRegistro
     */
    public mirarRegistro() {
        initComponents();
        // creo un aray ara los titulos del jTable
        String [] pedidos = {
            "ID del Pedido",
            "Nombre del Cliente",
            "Precio Total",
            "Producto",
            "Unidades",
            "fecha de venta",
            "fecha de entrega"
        };
        
        // asigno los titulos al modelo de datos para jTable
        modeloDatos.setColumnIdentifiers(pedidos);
        
        sql = "SELECT * FROM pedidos";
        
        // llamo al metodo llenarTabla pasando como parametros el atributo sql
        llenartabla(sql);
        
        jtRegistro.getColumn("ID del Pedido").setMaxWidth(80);
        jtRegistro.getColumn("Unidades").setMaxWidth(80);
    }
    
    private void llenartabla(String consultaSQL){
        // creo una conexion con el servidor
        mysql.crearConexion(false);
        
        // en el modelo de datos elimino todos los registros
        modeloDatos.setNumRows(0);
        
        // ejecuto la consulta sql que recibo como parametro
        ResultSet resul = mysql.ejecutarConsulta(consultaSQL);
        
        // creo un array con el nombre registro, recorro toda la tabla y agrego registro
        // por registro al modelo de datos
        try{
            while(resul.next()){
                String[] pedidos = {
                    resul.getString("id_pedidos"),
                    resul.getString("nom_cliente"),
                    resul.getString("precio"),
                    resul.getString("producto"),
                    resul.getString("unidades"),
                    resul.getString("fecha"),
                    resul.getString("entrega")
                };
                modeloDatos.addRow(pedidos);
            }
        }catch (Exception e) {
            // en caso de un error con la consulta muestro el siguiente error
            JOptionPane.showMessageDialog(null, "Error de SQL: " + e.getMessage(),
                    "Error de SQL", JOptionPane.ERROR_MESSAGE);
        }
        
        // cierro la conexion con el servidor
        mysql.cerrarConexion();
        
        // asigno el modelo al jTable (jtregistro)
        jtRegistro.setModel(modeloDatos);
    
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRegistro = new javax.swing.JTable();
        bRegresar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jlIDSeleccionado = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jToggleButton1.setText("Cancelar venta");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        jLabel8.setText("jLabel8");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mirar Registro de Pedidos");

        jtRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID del Pedido", "Nombre del Cliente", "Precio Total", "Producto", "Unidades", "Fecha y Hora", "Fecha de Entrega"
            }
        ));
        jScrollPane1.setViewportView(jtRegistro);

        bRegresar.setText("Atras");
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar venta");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jlIDSeleccionado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bModificar)
                                .addGap(18, 18, 18)
                                .addComponent(bCancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModificar)
                    .addComponent(bCancelar)
                    .addComponent(bRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlIDSeleccionado)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
       
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
       Modificar modificar = new Modificar();
       this.dispose();
       modificar.setVisible(true);
    }//GEN-LAST:event_bModificarActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        Principal principal = new Principal();
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_bRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mirarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mirarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mirarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mirarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mirarRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jlIDSeleccionado;
    private javax.swing.JTable jtRegistro;
    // End of variables declaration//GEN-END:variables
}
